NOAA-GFDL/MDTF-diagnostics

- src/util_mdtf.py
Hi Tom, this is my first time using git to commit/push/pull request so please educate me if I'm not doing it right. 
This is a simple change to src/util_mdtf.py to quit on error if a fieldlist file has the same convention as one that was already read. (This was my stupid errror in trying to write a new convention but failing to change the name of the convetion, only the file... however I think it will be a frequently-made stupid error so it deserves an error message). 
Also I'm new to writing Exceptions so I won't be insulted if you don't think it should be done the way I've done it.
> Code fails with error message if a fieldlist file repeats an existing convention

- doc/sphinx/ref_envvars.rst
- doc/sphinx/ref_settings.rst
Refine documentation on the POD's settings file and environment variables, in advance of the telecon. All changes except the first are fully backward-compatible.
- Correct suffix for dimension coordinate env var names from "_dim" to "_coord" [the latter is what the code currently uses; the docs were in error.]
- Add "<dim name>_bnds" env vars for names of coordinate bounds variables.
- Add optional "axis" attribute to dimensions section.
- Emphasize role of varlist path_variable environment variable for finding model data and define a default name for it.
- Wording changes and longer explanations.
> Update reference on POD settings and env vars

- doc/conf.py
- doc/copy_external_docs.py
The v3-beta3 release broke the readthedocs website (e.g., the table of contents sections for site-specific info and the POD descriptions are currently missing on https://mdtf-diagnostics.readthedocs.io/en/latest/). This PR cherry-picks the configuration file and external_docs extension from PR NOAA-GFDL/MDTF-diagnostics#141, which is the minimal number of files needed to fix this bug. (The contents of the files contain additional updates from NOAA-GFDL/MDTF-diagnostics#141 which aren't needed to fix this bug and don't introduce new bugs; I'm submitting them as-is rather than reverting these changes.)
Contents of the PR build correctly on readthedocs.com : https://mdtf-diagnostics-test-docs.readthedocs.io/en/feature-rtd-bugfix/
**Checklist:**
> Commit docs files needed to fix RTD build

- .travis.yml
- src/conda/conda_env_setup.sh
This PR adds a CLI flag, `--mamba`, to the conda_env_setup.sh script in order to install the package's environments using [mamba](https://github.com/mamba-org/mamba), a faster drop-in replacement for conda's dependency resolution mechanisms. Mamba is assumed to have been installed into the current conda environment by the user. The travis.yml configuration is updated to use this option.
No changes are made to any of the conda environments installed by the package, or to the runtime code (activating/deactivating environments for the framework and individual PODs), because none are needed -- mamba will tell you to use conda for activating/deactivating environments that already exist. Mamba is only invoked during environment installation.
This PR **does not** change the user …
> Use mamba for conda environment installs in CI

- README.md
This PR adds step-by-step instructions for new users and new developers to install MDTF using the CLI to the README.md file.
Associated issue [#151](https://github.com/NOAA-GFDL/MDTF-diagnostics/issues/151)
N/A
**Checklist:**
> Add step by step install instructions to README

- .travis.yml
- src/conda/conda_env_setup.sh
The previous PR (#163) only used mamba in Travis CI, and did not present this functionality to users. Based on the positive reception at today's meeting, the current PR edits the install script to always use mamba in a way that will be transparent to the user.
If the mamba executable isn't on the $PATH when conda_env_setup.sh is invoked, the installation is bootstrapped by first creating a temporary conda environment named "_MDTF_install_temp" and installing only the mamba package in it. If this is done, the environment is deleted after the installs. The `--mamba` flag on conda_env_setup.sh has been removed -- no documentation changes are needed, since now conda_env_setup.sh is used the same as before.
Associated issue # (#160)
Confirmed …
> Always use mamba for conda env installs

- mdtf_framework.py
- src/core.py
- src/mdtf_info.py
- src/util/logs.py
The following set of errors in identifying and specifying PODs were treated as non-fatal (affected PODs were ignored). This PR changes these to fatal errors, logging a relevant error message and exiting immediately.
- Missing settings.jsonc file
- JSON syntax errors in the settings.jsonc file (error message from python's json parser is passed through).
- Missing 'settings' or 'varlist' section in settings.jsonc file
- User requests a POD not that wasn't found or recognized, either in the run-wide `pod-list` or in a case-specific `pod_list` 
Associated issue #: NOAA-GFDL/MDTF-diagnostics#179
Verified that correct output was logged when the above conditions were met.
**Checklist:**
> Improve error handling for POD mis-specification

- .github/workflows/mdtf_tests.yml
- src/core.py
Fixes bug introduced by PR NOAA-GFDL/MDTF-diagnostics#183 which caused case list to never be recognized.
This bug was caught by CI (https://github.com/NOAA-GFDL/MDTF-diagnostics/runs/2327438137) after the PR was merged.   To catch errors such as these earlier, change the GitHub actions configuration to run the existing test suite on all PRs targeting the /develop or /main branches.
Reproduced error on local test case, and verified that the commit fixed the issue (package ran to successful exit). Changes to GH actions haven't been tested.
**Checklist:**
> Critical bug fix for case list parsing

- sites/NOAA_GFDL/default_gfdl.jsonc
Fix a typo in the OBS_DATA_REMOTE path defined in the default_gfdl.jsonc file
**Checklist:**
> Fix the default_gfdl.jsonc OBS_DATA_REMOTE path

- src/data_manager.py
- if v.is_static() is True, skip over calling
change_coord() for the time axis (T)
operating system(s) …
> Exit change_coord() if old/existing coordinate is not present

- src/xr_parser.py
This PR introduces changes to `xr_parser.py` towards better support of 2-dimension coordinates common to ocean and ice model grids.  The first change distinguishes between the variable coordinates and variable dimensions and assumes that if the number of coordinates is greater than the number of dimensions, we have a variable with a non-standard grid.
The second change makes the variable checking more permissive since cf-xarray still need to support `nlat` and `nlon` when inferring X and Y coordinates. 
Associated issue #198  
such as the Python version, package versions, …
> Fix for reading 2D coordinates common to ocean & ice model grids

- data/fieldlist_CMIP.jsonc
This PR adds variables required by new PODs to fieldlist_CMIP.jsonc
Associated issue #134 
**Checklist:**
> Add variables required by new PODs to the CMIP fieldlist file

- doc/sphinx/start_install.rst
Associated issue: #65
Closes #65 , since the MacOS CI configurations have already been updated to include XQuartz.
Instruct MacOS users to install XQuartz if they haven't already done so, in light of the debugging work done in #65. Adding another step to the installation is undesirable, but is the simplest workaround for the fact that the current [conda recipe](https://anaconda.org/conda-forge/ncl/files/modal/info/5ec553f3fe6b2a019f6937cf) for NCL doesn't include cairo (or other required graphics libraries -- again, it's unclear to me to what extent NCL's X11 dependency is hard-coded). It's beyond our scope to spend time fixing this upstream issue.
N/A - change to docs only
**Checklist:**
> Add XQuartz dependency to installation instructions

- README.md
- doc/conf.py
- doc/sphinx/dev_cheatsheet.rst
I've added a development cheatsheet with brief instructions on file locations and variable creation/reference in response to discussion #228 
**Checklist:**
> Add development cheatsheet to docs

- src/conda/_env_synthetic_data.yml
Add pytest to _env_synthetic_data.yml, which is required by the latest version of the synthetic data generator
**Checklist:**
> Add pytest to _env_synthetic_data.yml

- src/conda/_env_synthetic_data.yml
- src/conda/env_base.yml
- src/conda/env_convective_transition_diag.yml
- src/conda/env_dev.yml
- src/conda/env_python3_base.yml
Due to a known bug in Pandas v1.3.0, explicitly set the Pandas version to avoid error when the framework performs time slicing.
In this PR, all Python-based environments that use Xarray now have an entry to ensure that the Pandas version is less than v1.3.0.
Associated issue #254
This PR was tested by recreating all conda environments and running the `src/default_tests.jsonc` file with the framework
**Checklist:**
> Specify Pandas version in conda environments

- .github/workflows/mdtf_tests.yml
- Uses packaged, released version of the tool rather
than cloning the source code
operating system(s) …
> Pull synthetic data package from PyPi

- src/cli_plugins.jsonc
The configuration for the [CMIP6 local file data source](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_data_sources.html#cmip6-local-file-data-source) refers to a non-existent file. Change this to use the correct module and class name.
**Checklist:**
> Fix mis-specified code location for CMIP6 local file data source (develop)

- data/fieldlist_GFDL.jsonc
- sites/NOAA_GFDL/gfdl.py
- src/cli_plugins.jsonc
- src/data_manager.py
Three disjoint bug fixes to correct bugs found in running framework on CM4_piControl_c192_OM4p125_v5_proto1 high-res experiment:
d45e9db: Incorrect field names in the GFDL convention. Obtaining an up-to-date mapping from GFDL naming conventions to CF/CMIP conventions has been a persistent issue.
e4e190b: Incorrect date range query logic. Existing logic fails for the case of chunked data when the analysis period spans two or more chunks.
386e01d: Covert collection of paths to download (via gcp, for GFDL data sources only) from pandas Series to list, if this collection originated from a pandas DataFrame catalog.
Diff also shows 6f3cdbf, which should have been merged into develop as part of #244.
These fixes address bugs that were encountered in …
> Production fixes for bugs encountered on GFDL high-res expt

- sites/NOAA_GFDL/gfdl.py
- src/data_sources.py
Corrects bugs in GFDL CMIP6 DataSource classes which were introduced by PR #161. 
Bugs were encountered in testing PR #264 on CMIP6 data at GFDL. Verified that included fixed corrected the errors (PODs ran to completion using CMIP6 data from these sources) and that related bugs weren't present in code for other DataSources (which also would have been found in testing done for #161).
**Checklist:**
> Hotfix for GFDL CMIP6 DataSource bugs

- src/cli.py
- src/core.py
- src/data_manager.py
- src/data_sources.py
- src/environment_manager.py
- src/install.py
- src/mdtf_info.py
- src/util/exceptions.py
- src/verify_links.py
The python exit() function is not supported for non-interactive execution (see
https://docs.python.org/3.7/library/constants.html and https://stackoverflow.com/a/6501134); sys.exit() should be used instead. This commit replaces existing calls to exit() throughout the code by calls to a new wrapper function util.exit_handler() which calls sys.exit().
This is **not a critical bug**, because in practice when we hit a call to exit() we exit anyway, from the unhandled exception raised in this condition. 
Verified that exit_handler() is called during fatal error conditions, and that exception raised by calling exit() does not occurr.
**Checklist:**
> Bug fix: Replace exit() with sys.exit()

- doc/sphinx/ref_cli.rst
- mdtf_framework.py
- sites/NOAA_GFDL/cli_gfdl.jsonc
- sites/NOAA_GFDL/cli_plugins.jsonc
- sites/NOAA_GFDL/gfdl.py
- src/cli_template.jsonc
- src/core.py
- src/util/filesystem.py
- Describes which CLI flags are required, in online CLI help and Sphinx documentation website.
- Additional clarification on effects of site and plug-in settings 
- Correct default CLI paths for the GFDL site installation to new site installation location (taken from default_gfdl.jsonc values in 6b08ebf8e879ebac55e6a305a8a0178350fe3391)
- Print more explicit error messages if validation of input paths fails
- Check existence of CASE_ROOT_DIR before other validation. This is intended to catch input errors where arguments to CLI flags are parsed as positional arguments instead, e.g. https://github.com/NOAA-GFDL/MDTF-diagnostics/discussions/152#discussioncomment-1334531.
Associated issue #275 
Verified that modified sphinx documentation builds …
> Improvements to documentation on CLI settings

- src/xr_parser.py
The current cftime_cal definition assumes that the t_coord.values array contains the calendar attribute in its first element. However, the array is not populated after reading in some CMIP datasets that do not have the assumed metadata structure, which causes a framework crash when defining cftime_cal. This fix defines cftime_cal as None, then checks for the calendar attribute in t_coord.encoding. If the 'calendar 'attribute is not present here, the framework searches other t_coord and ds attributes for it.
Associated issue #284  
Tested on CentOS 8 using QBOI and AM4 test PODs and datasets in default_tests.jsonc
**Checklist:**
> Change cf_time calendar logic

- src/conda/env_python3_base.yml
The metpy package will support incoming the ocn_flux_matrix POD and others that require it
operating …
> Add metpy to python3_base yaml

- mdtf_framework.py
- Pass arguments explicitly rather than use only sys.argv
- Allows for the script to be called directly, (e.g. PyCharm Console)
**Checklist:**
- [x ] I have reviewed my own code to ensure that if follows the [POD development guidelines](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_guidelines.html)
- [x ] My branch is up-to-date with the NOAA-GFDL …
> Changed argument handling of mdtf_framework.py

- sites/NOAA_GFDL/gfdl.py
- src/data_manager.py
- src/data_model.py
- allows for `gfdl_component` to be specified in a
fieldlist*.jsonc file
- `gfdl_component` is a comma-separated string of
GFDL frepp components in preferential order
- Preferred components are honored before the other
existing heuristics
- Changed "component" to "expt_key" in GFDL
`resolve_pod_expt` (not sure how this worked before,
possible bug?)
Associated issue #335
- Added optional `gfdl_component` to `fieldlist_CMIP.jsonc`:
```
"sos": {
"standard_name": "sea_surface_salinity",
"units": "psu",
"ndim": 3,
"gfdl_component": "ocean_monthly_1x1deg"
},
"tos": {
"standard_name": "sea_surface_temperature",
"units": "degC",
"ndim": 3,
"gfdl_component": "ocean_monthly_1x1deg,ocean_monthly"
},
```
- Ran the example diagnostic and requested tos, sos …
> Support for preferred GFDL frepp components

- src/conda/env_base.yml
- src/conda/env_python3_base.yml
Move OM4labs packages and dependencies from env_base.yml to env_python3_base.yml
**Checklist:**
> Remove OM4labs and dependencies from MDTF base yaml

- .github/PULL_REQUEST_TEMPLATE.md
- doc/sphinx/dev_start.rst
> change required python version to 3.7 in PR template

- src/core.py
Resolve error when `_tags` argument is passed to logger:
```
TypeError: _log() got an unexpected keyword argument 'tags'
```
by defining it as a nested 'extra' keyword argument as explained [here](https://forum.sentry.io/t/how-to-add-tags-to-python-logging/323/4)
Associated issue #352 
Tested with Python 3.7 on Linux OS with latest main branch updates using `--disable-preprocessor` option
**Checklist:**
> define _tags kwarg as an 'extra' kwarg

- src/conda/env_python3_base.yml
https://github.com/raphaeldussin/om4labs/issues/108 …
> Add intake-xarray to env_python3_base.yml

- sites/NOAA_GFDL/mdtf_frepp_template.jsonc
- sites/NOAA_GFDL/mdtf_gfdl.csh
GFDL MDTF FREPP wrapper script update, includes a gfdl mdtf frepp template jsonc.
Associated issue #349  
Yes
**Checklist:**
> Frepp wrapper for MDTF

- sites/NOAA_GFDL/mdtf_frepp_template.jsonc
- sites/NOAA_GFDL/mdtf_gfdl.csh
- src/conda/env_python3_base.yml
> Merge mdtf gfdl csh script updates into develop branch

- sites/NOAA_GFDL/gfdl.py
- sites/NOAA_GFDL/mdtf_frepp_template.jsonc
- sites/NOAA_GFDL/mdtf_gfdl.csh
- src/conda/env_python3_base.yml
When the data manager is allowed to pull variables from different GFDL components, this fix allows the preferred variable functionality to extend down to the variable level. Previous implementation was only at the POD level.
Associated issue #335
Standard CI
**Checklist:**
> Bugfix: allow preferred component to extend to the variable level

- src/data_manager.py
- src/data_model.py
- src/diagnostic.py
- src/preprocessor.py
This PR address issue #371 and allows for more control over the preprocessor when it comes to renaming coordinate variables.
Basic CI suite along with an `om4labs` POD branch that is currently in development.
**Checklist:**
> Toggle control of coordinate renaming via `rename_coords` attribute

- src/conda/env_base.yml
- src/conda/env_python3_base.yml
Add nc-time-axis conda package to the python3 env yaml
Associated issue #383 
**Checklist:**
> add nc-time-axis to python3 yaml

- sites/NOAA_GFDL/gfdl.py
Not all functions that are provided _filter_column accept the `preferred` kwarg. This fix only passes the `preferred` argument to the filter function if it is not None.
Standard CI suite.
**Checklist:**
> Fix for preferred component functionality

- src/data_manager.py
Add a check for an empty var.associated_files data frame before setting the expt_key entry to data_manager.query_dataset. 
Associated issue #386 
**Checklist:**
> Fix for undefined associated_files attribute

- src/conda/env_python3_base.yml
Update cartopy to v 0.21 or later to solve issue related to http timeout
Associated issue #405  
**Checklist:**
> update cartopy version in python3 conda environment file

- src/conda/env_python3_base.yml
Add cython to the python3_base conda env file to support the ETC_composites POD reqs.
**Checklist:**
> add cython to env_python3_base.yml

- .github/workflows/mdtf_tests.yml
- tests/github_actions_test_macos_set3.jsonc
- tests/github_actions_test_ubuntu_set3.jsonc
Add the STC Eddy Heat Fluxes POD to the Github Actions CMIP test suite
Tested with Python 3.7, Linux CentOS 8
**Checklist:**
> Add stc eddy heat fluxes POD to CI

- doc/requirements.txt
- src/conda/env_dev.yml
bump sphinx, recommonmark versions in doc requirements.txt add jinija2 specs to requirements.txt
Outdated packages, specifically jinja2, are causing the readthedocs build to fail when running conf.py.
Ran conf.py using the updated test environment specified by env_dev.yml
**Checklist:**
> bump package versions in doc requirements and env_dev yaml file

- src/conda/env_python3_base.yml
> bump xarray version to 0.20 or later in python3 base yaml

- diagnostics/temp_extremes_distshape/TempExtDistShape_CircComps_util.py
- src/conda/env_python3_base.yml
Running into issues with natural earth downloads timing out in mixed_layer_depth and seaice_suite PODs as described [here](https://github.com/SciTools/cartopy/issues/1298) . Testing to see if upgrading cartopy will resolve this.
**Checklist:**
> bump cartopy to v 0.21.0 to try and resolve issues with naturalearth

- src/xr_parser.py
update the variable attributes with the normalized values before decode_cf is called on the dataset. This ensures that the time calendar, and other attributes, are converted to values that decode_cf will accept in subsequent steps.
**Checklist:**
> update var attributes in pre_decode

- tools/rename_input_files/doc/rename_input_files.rst
- tools/rename_input_files/rename_input_files.py
switch soft linking of new files to creating copies to avoid issues with framework ingesting files in no_pp mode
update rename input files doc to reflect changes in script
**Checklist:**
> replace softlinks with copying in rename_input_files.py

- sites/NOAA_GFDL/mdtf_frepp_template.jsonc
> add data_type to mdtf_frepp_template.jsonc

- src/xr_parser.py
change argument `our_var` to `coord` in xr_parser call to `reconcile_scalar_value_and_coords`. The `our_var` value
may correspond to a `TranslatedVarlistEntry` instance for a dependent variable. Dependent variables do not have the is_static property , while coordinate variables do. `reconcile_scalar_value_and_coords` is only intended to work on coordinate data based on the preceding function calls that only work on `coord` and/or `ds[ds_coord_name]` in the logic block that iterates through coord values in an `our_scalars` array.
add error logging for assertion statements in `reconcile_scalar_value_and_coords`
Associated issue #449
Tested on RHEL-8 laptop with python 3.10 and prelim version of the stc_vert_wave_coupling POD with daily …
> Fix bug in xr_parser  reconcile_scalar_value_and_coords

- src/preprocessor.py
Fix convention argument passed to from_CF_name call by preprocessor.MultirunExtractLevelFunction
Associated issue #456 
**Checklist:**
> Fix multirun extract level function bug

- src/xr_parser.py
* add check for Z axis is ds_axes.keys before comparing other axes with length 1
* add error message to assertion statement in xr_parser.reconcile_dimension_coords
Associated issue #460 
Tested with RHEL 8, Python 3.10, CI
**Checklist:**
> fix bug in xr_parser.reconcile_dimension_coords

- data/fieldlist_NCAR.jsonc
- src/data_model.py
- src/preprocessor.py
- src/xr_parser.py
* update axes_values and _old_axes_dict xr_parser methods to allow for multiple variable coordinates associated with a dimension, and for the dimensions to differ from said coordinates
* allow time coordinates in CropDateRangeFunction process method to be lists in the event that a variable has multiple dimension coordinates
*  add Potential Temperature SST variable to NCAR fieldlist
Associated issue #465 
Tested on Linux RHEL8 OS w/Python 3.10
**Checklist:**
> Update preprocessor functions to allow multiple variable coordinates 

- .github/workflows/mdtf_tests.yml
comment out macos tests because of mamba failure.
I'll re-implement them once I find a solution
```
/Users/runner/miniconda3/condabin/mamba create --name test python=3.10.0
Warning: Traceback (most recent call last):
File "/Users/runner/miniconda3/condabin/mamba", line 7, in <module>
Traceback (most recent call last):
File "/Users/runner/miniconda3/condabin/mamba", line 7, in <module>
Warning:     from mamba.mamba import main
File "/Users/runner/miniconda3/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
import libmambapy as api
File "/Users/runner/miniconda3/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
raise e
File "/Users/runner/miniconda3/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
from …
```
> stop the macos tests in the ci

- sites/NOAA_GFDL/mdtf_gfdl.csh
The GFDL frepp wrapper works, but the error handling after running MDTF has two small problems.
1. Cshell sets variables with "set var = value" and does not accept the Bourne shell "var=value"
2. Cshell parses the "else if" clause even if the first case is true. bash/sh does not do this. (https://unix.stackexchange.com/questions/197497/how-to-check-if-string-is-blank-in-tcsh)
While testing the FRE Canopy prototype using the mdtf wrapper in the trunk, I encountered the pkg_status variable error and an "empty if" error that were resolved by these changes.
**Checklist:**
> Slight csh fixes for error handling for GFDL frepp wrapper

- diagnostics/temp_extremes_distshape/TempExtDistShape_FreqDist_util.py
Remove deprecated axis font size parameter specs from temp_extremes_distshape plot routine
RHEL8, python 3.11
**Checklist:**
> Fix temp_extremes_distshape POD

- src/conda/env_base.yml
Update intake-esm to v 2023.11.10 in env_base.yml
**Checklist:**
> bump intake-esm version in base yaml

- .github/workflows/sphinx_action.yml
- doc/index.rst
- doc/sphinx/dev_cheatsheet.rst
- doc/sphinx/dev_start.rst
Simple implementation of ammaraskar's Github action. Upon each pull request, this action will run and build the sphinx documentation.  Warnings will be then flagged in inline comments viewable in the files changed section of the PR. This PR also includes cleanup of various files.
Action was ran several times in forked repository. It warned about intentional errors.
**Checklist:**
> add sphinx build action on pull request

- src/conda/conda_env_setup.sh
Edited conda_env_setup.sh to resolve an issue with the `--force` flag while using mamba. Added an if statement that will use conda to remove envs that have the same name as the one to be created.
Built MDTF multiple times using this shell script and everything worked all fine!
**Checklist:**
> remove old conda envs if found on build

- src/preprocessor.py
Add logic to the preprocessor clean_nc_var_encoding method so that it checks types to determine the proper comparison syntax. This way, it won't fail on variable attributes that are not strings, and have lengths > 1.
Associated issue #514 
Tested on RHEL8 with Python 3.11
**Checklist:**
> fix logic in pp nc_var_encoding method

- diagnostics/MJO_suite/settings.jsonc
- src/pod_setup.py
- tools/catalog_builder/catalog_builder.py
Fix a few small bugs:
- catalog builder in cesm mode
- MJO_suite POD settings file 
- pod_setup.py assuming envs were under CONDA_ROOT
Run on my local machine with MJO_suite activated, envs not under CONDA_ROOT, and (tried) to build catalog in cesm mode (that still fails on my files but that is my files' fault, not the builder!)
**Checklist:**
- [x ] My branch is up-to-date with the NOAA-GFDL main branch, and all merge conflicts are resolved
- [x ] The repository contains no extra test scripts or data files
> Fixes for cesm catalog builder and MJO_suite settings file

- .gitmodules
- doc/sphinx/ref_submodules.rst
- doc/sphinx/ref_toc.rst
- mdtf_framework.py
- src/conda/env_base.yml
- templates/module_config.jsonc
- templates/module_config.yml
Adds initial support for launching submodules (e.g. TempestExtremes) that have a python wrapper. It also adds an example json file on how to define what functions one would like to call from the submodule.
Associated issue #516 
This was built using the entire MDTF on my thin client and demoed to @wrongkindofdoctor, while the TempestExtremes wrapper was built and ran on both my thin client and PPAN.
**Checklist:**
> initial submodule (TempestExtremes) support

- templates/module_config.yml
-fix issue preventing MDTF from launching using this yml 
ran on my thin client
**Checklist:**
> fix bug in module_config.yml

- tools/catalog_builder/catalog_builder.py
add the following attrs to the GFDL parser:
- end_time
- start_time
**Checklist:**
> add start_time and end_time attrs to catalog_builder.py

- data/fieldlist_CMIP.jsonc
- data/fieldlist_GFDL.jsonc
- diagnostics/stc_ozone/settings.jsonc
- tools/catalog_builder/catalog_builder.py
- tools/catalog_builder/examples/templates/example_builder_config.yml
* add entries to GFDL and CMIP fieldlists
* add custom parser for AM5 data to catalog builder
* add optional config file parameter to set the desired catalog parser
**Checklist:**
> Extend cat builder

- .all-contributorsrc
- README.md
#529 
PR is necessary to test, so creating a PR
> 529 contrib

- data/fieldlist_CESM.jsonc
- data/fieldlist_CMIP.jsonc
- data/fieldlist_GFDL.jsonc
- src/data_model.py
- src/data_sources.py
- src/pod_setup.py
- src/preprocessor.py
- src/translation.py
- src/units.py
- src/util/catalog.py
- src/varlist_util.py
* refactor the translation module to parse additional coordinate information from the CMIP CV tables
* add from_convention parameter to reference pod_convention to translate from
* update translate_coord logic to use coordinate values when defining scalar_coords
* add new variables and refs to gfdl_to_cmor jsons to the GFDL fieldlist
* add an N coordinate to the data_model coordinate classes for entries are not X,Y,Z,T
such as the Python version, package versions, expected POD wallclock time, …
> Refactor translator

- tools/catalog_builder/catalog_builder.py
* add __init__.py files to tools and catalog_builder directories
* add the src directory to the system path before importing src/util to catalog_builder.py
Associated issue #562 
RHEL8 with Python 3.11
**Checklist:**
> fix catalog builder src module imports

- src/preprocessor.py
- src/util/datelabel.py
Add of simple logic to return the DateFrequency object in the type of str for use in the catalog query. Can be spun out into a match-case statement instead for further specificity.
**Checklist:**
- [x ] My branch is up-to-date with the NOAA-GFDL main branch, and all merge conflicts are resolved
- [ x] My code is portable; it uses [MDTF environment variables](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_envvars.html), and does not …
> add logic to format method of DateFrequency object

- src/data_model.py
- src/data_sources.py
- src/preprocessor.py
- src/translation.py
- src/varlist_util.py
* move preprocessor function edit_request calls before the catalog query
* Update PrecipRatetoFlux and ExtractLevelFunction edit_request methods to work with new translator objects
* Fix translated varlist entry scalar coords so that they are instances of VarlistEntry[X,Y,Z,T,N]Coordinate instead of OrderedDicts for consistency and to ensure that all necessary attributes are accessible to preprocessor functions.
such as the Python version, package versions, expected POD wallclock time, and the …
> Fix issues with preprocessor functions

- src/util/datelabel.py
**Checklist:**
- [ x] My branch is up-to-date with the …
> fix conditional in datelabel.py

- src/preprocessor.py
- src/util/datelabel.py
**Checklist:**
- [x ] My branch is up-to-date with the …
> fix check_group_daterange function in preprocessor.py

- src/data_model.py
- src/preprocessor.py
- src/translation.py
* Update pp query to search for level-specific and 4D variables if necessary 
* define the name correctly in precip rate to flux edit_request
* move the new translated varlist object with 4D information to an alternate entry to query if no level-specific variable is found in the catalog in extract level function edit_request
* incorporated existing catalog query updates from @jtmims
operating system(s) you ran …
> More pp fixes

- src/data_model.py
- src/preprocessor.py
- src/translation.py
> Fix issues with coordiante is_scalar attribute

- src/xr_parser.py
fixes an issue wherein xr.decode_cf drops required attributes.
**Checklist:**
- [x ] The repository contains no extra test scripts or data files
> reattch calendar attr after xr.decode_cf()

- src/preprocessor.py
**Checklist:**
- [ x] The repository contains no extra test scripts or data files
> remove | operator from query_catalog

- src/conda/env_python3_base.yml
Add packages required by the finite amplitude wave diagnostics POD to the python3 base environment file.
**Checklist:**
> add packages required by faw diag to python3 base yaml

- src/preprocessor.py
- src/xr_parser.py
I would like to acknowledge John for bestowing this Xarray knowledge to me.  
**Checklist:**
- [x ] The repository contains no extra test scripts or data …
> grab attrs from ds.time.encoding instead of reattaching

- src/preprocessor.py
- src/util/datelabel.py
change error to warning in check_contiguous_span method and add check for empty dataframe reutrned by check_group_daterange
**Checklist:**
> fix issues with check_group_daterange

- src/preprocessor.py
Fix the concatenation scheme for the xarray dataset returned by function. This also adds a check to make sure we only pass files that are within the user-specified date range.
**Checklist:**
- [ x] The repository contains no extra test scripts or data files
> fix cat_dict concatenation in query_catalog

- src/preprocessor.py
**Checklist:**
- [x ] The scripts are written in Python 3.11 or above (preferred; required if funded by a CPO grant), NCL, or R
- [ x] The repository contains no extra test scripts or data files
> fix to write single variable with POD's convention in write_dataset

- mdtf_framework.py
- src/preprocessor.py
- src/util/catalog.py
> create function rename_dataset_vars and fix in catalog.py

- mdtf_framework.py
- src/data_sources.py
- src/preprocessor.py
- src/util/catalog.py
- src/util/filesystem.py
* Refactor write_pp_catalog to populate output catalog columns with information from input catalog and case varlist attributes
* remove deprecated classes and methods from data_sources and catalog modules
* add realm back to catalog query
* fix temp_dir_root definition in filesystem module
**Checklist:**
> Refactor catalog write

- diagnostics/forcing_feedback/settings.jsonc
**Checklist:**
- [x ] The scripts are written in Python …
> fix settings file for forcing_feedback

- src/preprocessor.py
- src/util/catalog.py
* replace variant_label with member_id in catalog assets
* add member_id and remove activity_id from aggregation contro
* define project_id instead of convention column in preprocessor write_pp_catalog
Associated issue #588 
**Checklist:**
> update mdtf output catalog columns

- src/preprocessor.py
> uncomment writing file terminal message

- diagnostics/MJO_suite/MJO_suite.py
- diagnostics/MJO_suite/mjo.ncl
- diagnostics/MJO_suite/mjo_EOF.ncl
- diagnostics/MJO_suite/mjo_EOF_cal.ncl
- diagnostics/MJO_suite/mjo_lag_lat_lon.ncl
- diagnostics/MJO_suite/mjo_life_cycle.ncl
- diagnostics/MJO_suite/mjo_spectra.ncl
* fix refs to WORK_DIR and startdate, enddate in MJO_suite ncl files
* fix typo in MJO_suite driver script
**Checklist:**
> Fix MJO suite env vars

- src/preprocessor.py
- src/util/datelabel.py
* add support for string time_range values to preprocessor check_date_range function
* add support for date ranges with multiple delimiters to datelabel DateRange init method
**Checklist:**
> Add support for string time_ranges and date ranges with multiple delimiters

- diagnostics/MJO_suite/daily_anom.ncl
- diagnostics/MJO_suite/daily_netcdf.ncl
- diagnostics/MJO_suite/mjo.ncl
- diagnostics/MJO_suite/mjo_EOF.ncl
- diagnostics/MJO_suite/mjo_EOF_cal.ncl
- diagnostics/MJO_suite/mjo_lag_lat_lon.ncl
- diagnostics/MJO_suite/mjo_life_cycle.ncl
- diagnostics/MJO_suite/mjo_spectra.ncl
Fix an issue where diagnostics/MJO_suite/daily_netcdf.ncl could not write files. Updated file_dir in the rest of the .ncl files.
**Checklist:**
> change file_dir variable and fix writing error in MJO_suite

- src/preprocessor.py
> add var.log.info message for catalog query

- src/preprocessor.py
> fix typo in query_catalog error msg

- src/preprocessor.py
Added a new case to allow for monthly data to not throw a ValueError in check_group_daterange
**Checklist:**
> add monthly date_format in check_group_daterange

- src/varlist_util.py
add logic to VarlistEntry.from_struct to set realm from pod global_env_vars if provided instead of assuming realm attribute is defined for each pod variable
**Checklist:**
> fix realm definition in varlistentry.from_struct

- src/preprocessor.py
Variables would overwrite the processing done by the execute functions in the preprocesser for the previous variables. Rewrote the process function to place processed variables into the cat_subset directly. This fixes issues with “pr”.
**Checklist:**
> prevent overwriting processed variables during execute_pp_functions

- src/cli.py
- src/preprocessor.py
- src/util/datelabel.py
* add support for yyyy and yymm startdate and enddate precision to the framework cli
* put in dummy day date precision for startdate and enddate defined as yymm or yyyy to datelabel
*  remove cropdaterangefunction call from preprocessor execute wrapper as this functionality has been added to checkgroupdaterange during the catalog query. Retain function in code for reference in case extra start/end time refinement is required
RHEL8
**Checklist:**
> add support for yyyy, yyyymm to start and end dates

- src/preprocessor.py
- src/units.py
* add logic that checks each variable standard_name and long_name for exact and approximate matches of the input name to units.convertdataarray
* change the parameter from name to standard_name when the preprocessor calls the function on a coordinate
* update the standard_name value of the input variable updated by convertdataarray if it is not defined
RHEL8
**Checklist:**
> add logic to check standard and long names to convertdataarray function

- src/preprocessor.py
- src/util/__init__.py
- src/util/basic.py
- src/varlist_util.py
- src/xr_parser.py
* refactor alternates as an attribute list of VarlistEntry objects associated with the primary variable VarlistEntry object
* add calls to translate alternate variables if able
* update logic in preprocessor query_catalog to search alternate translation objects if present and update query name, standard name accordingly
**Checklist:**
> Add alternate support

- diagnostics/forcing_feedback/forcing_feedback_plot.py
- diagnostics/forcing_feedback/forcing_feedback_util.py
- src/preprocessor.py
- src/xr_parser.py
Uncomment reconcile_variable with a slight fix to allow it to run with the current catalog implementation. This PR also fixes some filepath issues found in forcing_feeback.
**Checklist:**
> reimplement reconcile_variable and fix pathing issues in forcing_feeback

- README.md
- doc/sphinx/start_install.rst
- src/conda/env_NCL_base_micromamba.yml
- src/conda/env_base_micromamba.yml
- src/conda/env_python3_base_micromamba.yml
- src/conda/micromamba_env_setup.sh
* add separate environent files for micromamba installation without packages that solver cannot find
* update the micromamba build script to reference the new files
* add notes to README and docs about differences between the conda and micromamba enviroments
Associated issue #605 
macOS Sonoma w/micromamba, python3
**Checklist:**
> Add separate environment files for micromamba installation

- src/conda/env_python3_base.yml
> remove redundant pip intall lines from env_python3_base.yml

- src/preprocessor.py
Sometimes, the varlist.T.frequency is of type string instead of the custom DateFrequency. This adds logic to handle that. The process function in the preprocessor would sometimes drop parsing done on bounds. The added for loop makes the edits done by the parser be explicitly added to the cat_subset.
**Checklist:**
> add logic for query freq and make parsing in process more explicit

- src/preprocessor.py
> add exception list of vars to prevent overwriting in preprocessor

- src/preprocessor.py
- src/xr_parser.py
Add support for multi-value scalar coordinates (e.g., plev19) in xarray dataset to preprocessor and xr_parser functions
RHEL8
**Checklist:**
> Fix xr parser issues

- diagnostics/top_heaviness_metric/settings.jsonc
add frequency entry to top_heaviness_metric pod settings file
**Checklist:**
> add frequency entry to top_heaviness_metric pod settings file

- src/environment_manager.py
- src/pod_setup.py
- src/util/logs.py
* add alternate var env vars to main env_var list passed to pod via subprocessruntime manager
* redefine pod children attribute
* add check to logs for None value for iter_children change child parm to False for final POD log
**Checklist:**
> fix issues in environment_manager env_vars and pod logging

- src/pod_setup.py
> add logic to convert pod_env_vars to strings

- diagnostics/forcing_feedback/forcing_feedback.html
- diagnostics/forcing_feedback/forcing_feedback_kernelcalcs.py
- diagnostics/forcing_feedback/forcing_feedback_plot.py
- diagnostics/forcing_feedback/forcing_feedback_util.py
fix forcing feedback figure paths
**Checklist:**
> fix forcing_feedback paths

- src/output_manager.py
* change logic switches to in HTMLOutputManager init
* fix paths in output_manager.cleanup_pod_files
**Checklist:**
> fix output_manager cleanup

- diagnostics/EOF_500hPa/compute_anomalies.ncl
> update path to check in compute_anomalies.ncl

- src/output_manager.py
> add call to remove model/PS files to cleanup_pod_files

- src/preprocessor.py
* reimplement date range check in query stage in new check_time_range routine
* move prior CropDateRangeFunction routines to MDTFPreprocessorbase
*  delete old CropDateRangeFunction class and methods
RHEL8
**Checklist:**
> reimplement date range checks in catalog query

- data/fieldlist_CESM.jsonc
> add 'precipitation_flux' to CESM fieldlist

- src/output_manager.py
- src/pod_setup.py
update definitions and refs to multicase_dict attribute in pod_setup and output_manager
**Checklist:**
> fix multicase_dict pod attribute

- mdtf_framework.py
- src/data_model.py
- src/data_sources.py
- src/environment_manager.py
- src/pod_setup.py
- src/preprocessor.py
- src/util/path_utils.py
- src/varlist_util.py
* fix issues with pod paths overwriting settings when new pod object is instantiated
* refactor varlist configuration so that varlistentries can be appended for each pod
* update preprocessor freq entry in query to use the variable spec instead of the case spec
* add line to delete problem height attribute from queried xarray dataset
MacOS Sonoma with example and ocn_surf_flux_diag PODs on synthetic data
**Checklist:**
> Fix multi-pod implementation

- src/varlist_util.py
fix issues with alternate variable configuration in VarlistEntry.from_struct
**Checklist:**
> fix alternates

- src/environment_manager.py
- src/output_manager.py
- src/pod_setup.py
- src/verify_links.py
* Fix refs to pod multicase_dict attribute and CASE_NAME entry in output_manager and environment_manager
* fix pod name definition in group_relative_links
**Checklist:**
> Fix pod multicase dict

- src/preprocessor.py
- src/util/datelabel.py
> spin out to function and extend match case for date format

- src/data_sources.py
- src/pod_setup.py
- src/preprocessor.py
- src/translation.py
- src/varlist_util.py
* fix attribute refs in varlistentry translator setup
* update parameter names in precipratetoflux edit_request
* update xarray dataset standard_name attribute after precip units conversion is applied
* add precip variables list to cross reference when querying the lookup table of convention to use for the translation
**Checklist:**
> Fix translator

- diagnostics/precip_diurnal_cycle/pr_diurnal_cycle.ncl
- diagnostics/precip_diurnal_cycle/pr_diurnal_phase.ncl
> fix pathing and date_offset issues in pr_diurnal_cycle

- diagnostics/MJO_suite/mjo.ncl
- diagnostics/MJO_suite/mjo_spectra.ncl
- diagnostics/precip_diurnal_cycle/pr_diurnal_phase.ncl
- diagnostics/precip_diurnal_cycle/precip_diurnal_cycle.py
- src/util/datelabel.py
* fix path defs in precip_diurnal_cycle and MJO_suite ncl scripts
* fix formatting in precip_diurnal_cycle driver script fix formatting in datelabel comments
**Checklist:**
> Fix pod paths and util formatting

- doc/sphinx/ref_output.rst
- doc/sphinx/ref_toc.rst
> add documentation to serve as a reference to MDTF output

- doc/sphinx/ref_output.rst
> fix typo in ref_output.rst

- src/preprocessor.py
- src/util/catalog.py
- tools/catalog_builder/catalog_builder.py
remove time_range from catalog aggregation_control template column
remove time_range debugging check from preprocessor 
Rhel 8, MacOS Sierra, Python 3.12
**Checklist:**
> Fix cat templates

- diagnostics/example_multicase/esm_catalog_CMIP_synthetic_r1i1p1f1_gr1.json
- src/util/catalog.py
- tools/catalog_builder/catalog_builder.py
remove time_range from groupby_attrs in catalog_builder, example json, and util/catalog.py
Macos Sierra, Python 3.12
**Checklist:**
> no more time_range in groupby_attrs templates

- src/conda/env_base.yml
- src/conda/env_base_micromamba.yml
- tools/catalog_builder/catalog_builder.py
* bump ectools version in base env files
* clean up catalog builder custom parsers
* add json utils to read information from fieldlist tables
**Checklist:**
> catalog builder updates

- src/preprocessor.py
* Add logic to delete attributes that create conflicts in xarray merge
* add option compat='no_conflicts' to xarray merge call in preprocessor"
RHEL 8 Python 12
**Checklist:**
> delete confusing attributes

- src/preprocessor.py
> add date to drop_vars

- src/xr_parser.py
> fix variable typo in reconcile_names

- src/preprocessor.py
> add logic to handle unexpected type in check_group_daterange

- mdtf_framework.py
- src/cli.py
> add function to verify that conda dirs exists after parsing config file

- src/conda/env_python3_base.yml
- src/conda/env_python3_base_micromamba.yml
add updated falwa package and gfortran dependency to python3_base env files
**Checklist:**
> add falwa package to python3 base env files

- src/preprocessor.py
- src/util/datelabel.py
> rework check_group_daterange to work with data starting at year 0001

- src/cmip6.py
- src/data_model.py
- src/environment_manager.py
- src/preprocessor.py
- src/translation.py
- src/util/basic.py
- src/util/dataclass.py
- src/util/filesystem.py
- src/util/logs.py
- src/verify_links.py
* clean up poor syntax and typos in docstrings
* clean up formatting
* remove unused signal_logger parameter
**Checklist:**
> Clean up docstrings

- mdtf_framework.py
Associated issue #676 
**Checklist:**
> add check for correct config file path to framework driver

- diagnostics/SM_ET_coupling/settings.jsonc
- diagnostics/forcing_feedback/settings.jsonc
- diagnostics/stc_eddy_heat_fluxes/settings.jsonc
- diagnostics/stc_qbo_enso/settings.jsonc
- diagnostics/stc_spv_extremes/settings.jsonc
- diagnostics/top_heaviness_metric/settings.jsonc
- doc/sphinx/pod_settings.rst
- src/varlist_util.py
update settings files in existing PODs with global realm settings update settings file docs
**Checklist:**
> move global realm setting to pod data section

- src/preprocessor.py
* add checks for variable is_static=True before performing time-related query functions in the preprocessor
* add logic to pp xarray concatenation procedure to check for static variables and concatenate along the Y,X,or N dimension
Associated issue #684 
RHEL 8, Python 3.12
WWEs POD
**Checklist:**
> add static variable support to preprocessor

- src/preprocessor.py
> infer 'start_time' and 'end_time' from 'time_range' due to type issues

- src/preprocessor.py
Line setting date_range was too early in the logic. Static vars would reach this line and cause an error.
**Checklist:**
> move line setting date_range in query_catalog()

- src/environment_manager.py
> add escape brackets to command-line commands

- data/gfdl-cmor-tables/gfdl_to_cmip5_vars.csv
> add ua200-850 and va200-850 to gfld-cmor-tables

- data/fieldlist_GFDL.jsonc
Add sea ice and ocean precip entries to GFDL field table. Included note to modify framework to allow lists of strings for realm entries
**Checklist:**
> add ice/ocean precip entries to GFDL fieldlist

- data/fieldlist_CMIP.jsonc
- data/fieldlist_GFDL.jsonc
- src/data_model.py
- src/preprocessor.py
- src/translation.py
- src/varlist_util.py
* define rainfall_flux and precipitation_flux entries in CMIP and GFDL fieldlists with new alternate_standard_names attribute
* add alternate_standard_names to the translated_variable standard_name query
* This may cause failure in the xr.parser reconcile var_names or attributes, so may need to iterate
Associated issue #698 
RHEL8, python 3.12
**Checklist:**
> Add alternate standard names entry to fieldlists and varlistEntry objects

- src/preprocessor.py
The MDTF would run into an issue if multiple chunk_freqs would exist in a dataset. This new function checks to see if that is an issue. If it is, it grabs the grabs the files whose 'chunk_freq' is the largest number where endyr-startyr modulo chunk-freq is zero and throws out the rest.
Associated issue #700  
This has been tested with a CM4.5 dataset with the issue on the GFDL network. Various other non-problematic dataset were ran to insure the function doesn't overstep its bounds.
**Checklist:**
> add function check_multichunk to fix issue with chunk_freqs

- src/html/pod_error_snippet.html
This PR adds a hyperlink to the main index.html for PODs that suffer an error. The error warning still shows, but now users are able to see the rest of the plots that completed normally. This helps with DORA integration.
**Checklist:**
> add plots link to pod_error_snippet.html

- src/output_manager.py
Currently, the MDTF holds onto all of the preprocessed data in the WORK_DIR, and it only removes the data in each POD's dir. This PR goes in an removes the rest of the .nc files if "save_pp_data" is set to false in the config file. It is done by using the "case_info.yml" file found in each POD dir. This will help conserve space for runs of the MDTF that involve many PODs.
Associated issue #702
The framework was ran on multiple GFDL datasets and with various PODs on my workstation.
**Checklist:**
> remove .nc files found in OUTPUT_DIR depending on config file

- doc/sphinx/ref_output.rst
Fixes some slight documentation issues I noticed while looking into the output reference.
**Checklist:**
> fix formatting issues in output reference documentation

- src/preprocessor.py
@aradhakrishnanGFDL  noticed an issue where all of the entries in the pp_catalog had the same name. This PR adds an update to the dict passed to make the catalog for the 'standard_name' of each variable. 
Associated issue #672 
Ran for MJO_suite and Wheeler_Kiladis on the workstation with some GFDL data.
**Checklist:**
> update 'standard_name' for each var in write_pp_catalog

- README.md
- doc/sphinx/start_install.rst
Removes documentation that states the --env_dir is an optional flag
Associated issue #712  
**Checklist:**
> Update docs about --env_dir flag

- doc/sphinx/start_config.rst
- src/pod_setup.py
- src/preprocessor.py
- src/translation.py
- tests/github_actions_test_ubuntu_1a.jsonc
> Fix dummy translation method in NoTranslationFieldlist

- data/fieldlist_GFDL.jsonc
- diagnostics/seaice_suite/seaice_suite_sic_mean_sigma.py
- src/data_sources.py
- src/preprocessor.py
- src/units.py
- src/xr_parser.py
A variety issues were found in the preprocesser while trying to run the seaice_suite on CM4.5 data. These issues resolved in the PR are as follows:
1. The realm_regex would grab files from an adjacent ice pp dir. This was fixed by spinning out the setting of case_d.query in the class for each convention (i.e. CMIP, GFDL, and CESM)
2. Add siconc to the GFDL data fieldlist
3. Create PercentTo01Function function to handle conversion for the unit ``0-1`` as cfunits does not handle this
4. Add logic to conversion_factor to return 1 if the units have the same string value
5. fix file path issue in POD
6. fix issues caused by multiple coords per axis
someone can …
> Fix various pp issues related to running seaice_suite

- diagnostics/example_multicase/container_config_demo.jsonc
might need to actually point to micromamba for the example to work
operating system(s) you ran your …
> fix typo in container_config_demo.jsonc

- data/fieldlist_CESM.jsonc
- data/fieldlist_GFDL.jsonc
- tools/catalog_builder/catalog_builder.py
- tools/catalog_builder/parsers.py
* Add cesm parser to catalog builder
* refactor builder with parsers in a separate module
* move xarray metadata search to a separate function
* clean up unused imports
* Add entries to cesm and gfdl field lists
**Checklist:**
> Cesm cat builder

- src/conda/conda_env_setup.sh
> fix typo in conda_env_setup

- src/preprocessor.py
Write processed netcdf files as dask_delayed objects to improve performance, and add debugging time lines to write_dataset.
Tested on macOS with W-K POD using sample QBOI data
**Checklist:**
> Add dask_delayed nc write calls

- diagnostics/example_notebook/example_notebook.ipynb
- diagnostics/example_notebook/script.py
As notebooks become a feature that may be available to POD devs in the near future, I though it would be a good idea to update the example to showcase how external scripts would have to be called from the notebook in the MDTF-framework.
Ran on GFDL workstation using synthetic data
**Checklist:**
> add external script into example_notebook

- src/preprocessor.py
@nishsilva found an issue (#730) where his data couldn't get through crop_date_range. This was caused by the fact that the calendar attribute was hidden in the encoding of the time coord. After this, a new function had to be made to allow files that have differing time_units to pass through the preprocessor.
Associated issue #730  
Tested with ECMWF-LR output on my workstation to launch Nish's POD. I also tested the seaice_suite and Wheeler_Kiladis.
**Checklist:**
> add function to normalize all time coord units

- src/preprocessor.py
- src/xr_parser.py
The bounds attr was still found in the time coord after the bounds data was dropped. This PR makes sure this attribute is deleted from the coord. It also changes the conditional of an If statement to make sure we are only reconciling the variable asked by the function call.
Associated issue #730  
**Checklist:**
> del bounds attr from coord in drop_attributes()

- .github/workflows/mdtf_tests.yml
- README.md
- doc/sphinx/ref_container.rst
- doc/sphinx/start_install.rst
- templates/module_config.jsonc
- templates/runtime_config.jsonc
In the latest mdtf-test-data (1.0.9), the user is given a flag to set the frequency of the generated data. It also allows for the user to easily throw custom yml's into a direct install for more freq options for each data type. This PR adds the flag into the CI tests and documentation.
**Checklist:**
> add new --freq flag in mdtf-test-data to docs and tests

- doc/sphinx/ref_cli.rst
- src/cli.py
- src/data_sources.py
- templates/module_config.jsonc
- templates/module_config.yml
- templates/runtime_config.jsonc
- templates/runtime_config.yml
The wildcard inclusion in the realm column query causes issues returning unique values in large catalogs (e.g., it will include atmos and atmos_xxx in the query). The realm definition for GFDL data will need to be expanded.
**Checklist:**
> remove wildcard from realm_regex def

- src/conda/env_python3_base.yml
> downgrade xesmf to 0.8.7 to avoid package conflicts with esmf and esmpy

- README.md
- doc/sphinx/pod_requirements.rst
- doc/sphinx/start_config.rst
- doc/sphinx/start_install.rst
Updated documentation with Globus links for input (digested) obs_data, sample CESM data and incoming share directory for POD developers.
modified:   README.md
modified:   doc/sphinx/pod_requirements.rst
modified:   doc/sphinx/start_config.rst
modified:   doc/sphinx/start_install.rst
[Obs_data (digested, distributed to users)](https://app.globus.org/file-manager?origin_id=87726236-cbdd-4a91-a904-7cc1c47f8912&origin_path=%2F")
[Share (for incoming data from POD developers)](https://app.globus.org/file-manager?origin_id=620e84f2-1f5b-46b7-addd-06e9ba44cfac&origin_path=%2F")
[Timeslice CESM Data MDTFv3](https://app.globus.org/file-manager?origin_id=200c3a02-0c49-4e3c-ad24-4a24db9b1c2d&origin_path=%2F) 
[Timeslice CESM Data MDTFv1 (QBOi …
> Update documentation with Globus links

- src/preprocessor.py
variable_id was being populated with the name of the last variable read into xarray using the catalog_attrs attribute. This fix uses the correct variable id from the translation attribute
**Checklist:**
> fix variable_id definition in postprocessor catalog

- src/data_sources.py
- src/environment_manager.py
- src/preprocessor.py
- src/xr_parser.py
* Fix logic in preprocessor, data_sources, and xr_parser to check variable time is_static attribute
* update frequency on a per-variable basis if the attribute is available when writing the post processed data catalog
* fix env_vars attribute reference in the subprocessPodwrapper
Associated issue #748 
**Checklist:**
> Fix pp time defs

- data/fieldlist_CESM.jsonc
- data/fieldlist_CMIP.jsonc
- data/fieldlist_GFDL.jsonc
> add land area fraction to fieldlists

- src/data_sources.py
Using var.T.units will yield the wrong expected values in the catalog. The units are set in the date_range methods, and values such as 'mo' will not yield results when the frequency is queried, as the expected value would 'mon'
**Checklist:**
> define frequency using var.T instead of var.T.unit in set_query

- tools/catalog_builder/parsers.py
For some reason, catalogs outputted by our tool would fail for the case of GFDL convention. After digging through various ecgtool scripts, I realized we were not returning anything in our parser functions. Oops!
**Checklist:**
> add return statements to catalog_builder/parsers.py

- src/util/datelabel.py
> change monthly units assigned by datelabel from 'mo' to 'mon'

- data/fieldlist_CMIP.jsonc
Catalogs generated from the GFDL builder will populate rsds the 'standard_name' with 'downwelling_shortwave_flux_in_sea_water'. This is a needed fix to allow the forcing_feedback POD to run with catalogs generated on CM5 data.
**Checklist:**
> add alternate name for rsds in CMIP fieldlist

- src/preprocessor.py
- src/xr_parser.py
Add logic to bypass i,j coordinates if they are present in the coords attribute of a dataset during xr_parser name check. Irregular grids may map X, Y axes to i,j coordinates instead of longitude,latitude.
**Checklist:**
> i,j to lat lon

- src/output_manager.py
- src/util/path_utils.py
When using a work dir that was not the same as the output dir, some weird behaviors were observed. This PR is more direct with happens in the output_manager to take care of these behaviors.
Ran on workstation and GFDL analysis node
**Checklist:**
> fix implementation of overwrite flag in src/output_manager.py

- src/conda/_env_synthetic_data.yml
- src/conda/conda_env_setup.sh
- src/conda/env_base.yml
- src/conda/env_base_micromamba.yml
- src/conda/env_dev.yml
- src/conda/env_python3_base.yml
- src/conda/env_python3_base_micromamba.yml
Bump intake-esm and dependencies to latest versions in conda env files
Add -y flag to conda env create call in conda_env_setup.sh
**Checklist:**
> Bump intake esm version

- src/preprocessor.py
> remove debugging print statement from preprocessor.py

- data/fieldlist_GFDL.jsonc
- diagnostics/mar/SST_bias_NOAA_OISSTv2/SST_bias_NOAA_OISSTv2.html
- diagnostics/mar/SST_bias_NOAA_OISSTv2/SST_bias_NOAA_OISSTv2.ipynb
- diagnostics/mar/SST_bias_NOAA_OISSTv2/settings.jsonc
- src/data_sources.py
- src/environment_manager.py
- src/pod_setup.py
- src/preprocessor.py
- src/util/path_utils.py
This PR contains multiple changes to the framework to allow MAR notebooks to be integrated into the framework. This also includes instruction as to how to integrate a MAR notebook for future reference.
**How To MARxMDTF**
This is very similar to the normal way of integrating PODs. The first thing to note is the new dir structure introduced.
Making a tree from the code_root dir for the implementation of the SST_bias_NOAA_OISSTv2 MAR notebook:
```
mdtf/
└── MDTF-diagnostics/
└── diagnostics/
└── mar/
└── SST_bias_NOAA_OISSTv2/
├── settings.jsonc
├── SST_bias_NOAA_OISSTv2.html
└── SST_bias_NOAA_OISSTv2.ipynb
```
As you can see, this is all very standard practice for the MDTF. The only main difference is that the actual 'pod' is found inside of a further directory: `mar`. A directory named …
> Integrate MAR notebooks

- doc/sphinx/dev_gfdl.rst
- doc/sphinx/pod_dev_toc.rst
Add file dev_gfdl.rst with instructions for maintaining the MDTF_diag…nostics repo at GFDL under the oar.gfdl.mdtf role account
such as the Python version, package versions, expected POD …
> Update docs with GFDL role account instructions

- src/preprocessor.py
- src/units.py
- src/xr_parser.py
> Debug xr parser
