NOAA-GFDL/MDTF-diagnostics

.travis.yml
- Added job matrix
- Testing Mac OS 10.15.7
- Abstracted Miniconda installer url as environment variable
- Removed Python 2 as it is no longer supported
=> Implemented Mac OS Travis testing

doc/sphinx/dev_checklist.rst, doc/sphinx/dev_git_intro.rst
*  Updated the documentation with a requirement for POD feature branches to be up-to-date with the NOAA-GFDL develop branch
*  Added instructions for updating branches and fixing issues to the Git workflow file
* reformatted section and subsection headers in Git workflow files
*  added section Git Tips and Tricks to Git workflow files with information on updating global user names and emails, external merge tools, and helpful links.
Fixes issue #72
=> Update documentation user requirements and git instructions

doc/sphinx/dev_git_intro.rst
* remove duplicate instructions in Pushing to your remote feature branch and add reference to Working on a brand new feature
* update git instructions to reflect the new web interface design
Associated issue #173 
**Checklist:**
=> Update the documentation

src/conda/env_NCL_base.yml, src/conda/env_base.yml
Add subprocess to base yaml and nco to NCL yaml to support incoming PODs
**Checklist:**
=> Add base yaml pkgs

src/conda/env_base.yml
Added `cmocean` and `regionmask` via pip
Associated issue #338 
CI
**Checklist:**
=> Additional packages for base environment

sites/NOAA_GFDL/gfdl.py, sites/NOAA_GFDL/mdtf_frepp_template.jsonc, sites/NOAA_GFDL/mdtf_gfdl.csh, src/conda/env_python3_base.yml, src/data_manager.py, src/data_model.py, src/diagnostic.py, src/preprocessor.py
This PR adds support for specifying an `associated_files` attribute for a variable. This is implemented initially only for the GFDL-PP data manger and a variable's static file is:
- resolved
- fetched
- copied to _WKDIR_
- assigned the environment variable `<VARNAME>_ASSOC_FILES`
The `associated_files` name was chosen to be consistent with CF conventions and could be extended to the CMIP data manager.
**_This PR also introduces the equivalent functionality of the `set static = ....` shell functionality from fre-analysis_** 
This PR addresses the discussion #359.
Tested on the standard CI suite.
**Checklist:**
=> Add support for `associated_files`

README.md
Associated issue #368 
**Checklist:**
=> Add PODs to the readme.md file

diagnostics/ENSO_RWS/ENSO_RWS.html, diagnostics/ENSO_RWS/ENSO_RWS_04.html, diagnostics/ENSO_RWS/ENSO_RWS_05.html, src/preprocessor.py, src/xr_parser.py
* add logic to distinguish among string, numpy ndarray, and non-string iterable instances to variable attribute checks in xr_parser and preprocessing data cleaning routines
* remove references to a deleted pdf file from ENSO_RWS html files
Associated issue #382 
Tested with ENSO_RWS POD on GFDL analysis machine with CM3 historical data (in addition to GH Actions tests).
**Checklist:**
=> Add valid range handling

.github/workflows/mdtf_tests.yml
Update the github actions checkout to version 3.0
**Checklist:**
=> update checkout action from v2 to v3 in mdtf_tests.yml

src/conda/_env_synthetic_data.yml, src/conda/env_base.yml, src/conda/env_dev.yml, src/conda/env_python3_base.yml, src/environment_manager.py, src/output_manager.py, src/preprocessor.py, src/query_fetch_preprocess.py, src/xr_parser.py
add ecgtools package to the base environment
Tested on linux RHEL 8 system using python 3.10
=> update xarray and intake-esm conda packages

data/cmip6-cmor-tables/.circleci/config.yml, data/cmip6-cmor-tables/README.md, data/cmip6-cmor-tables/Tables/CMIP6_CV.json, data/cmip6-cmor-tables/scripts/CMIP6_CV_cron_github.sh, data/cmip6-cmor-tables/scripts/createCMIP6CV.py, src/tests/test_cmip6.py
Update scripts and CMIP6_CV.json in data/cmip6-cmor-tables
**Checklist:**
=> Update cmor tables

src/conda/env_base.yml, src/conda/env_dev.yml
Update intake-esm to 2023.07.07 to resolve dependency issue with pydantic
**Checklist:**
=> Update esm intake version

doc/conf.py
update logo path and version info in conf.py
**Checklist:**
=> Fix sphinx issues

src/preprocessor.py
Add logic to preprocessor cropdaterangefunction that sets the date_range start and end hours to the hours in the dataset if they do not begin at zero, since the framework only supports specifying start/end years or dates wotj tje format yyyymmdd . This is a workaround to support timeslice and similar datasets.
RHEL8 Python 3.11
**Checklist:**
=> Extend cropdaterangefunction

README.md, diagnostics/forcing_feedback/doc/forcing_feedback.rst, diagnostics/forcing_feedback/forcing_feedback.html, diagnostics/forcing_feedback/forcing_feedback.py, diagnostics/forcing_feedback/forcing_feedback_kernelcalcs.py, diagnostics/forcing_feedback/forcing_feedback_plot.py, diagnostics/forcing_feedback/forcing_feedback_util.py, diagnostics/forcing_feedback/obs_processing_script.py, diagnostics/forcing_feedback/settings.jsonc
Copy of POD/forcing_feedback miami branch with missing files in PR https://github.com/NOAA-GFDL/MDTF-diagnostics/pull/505 removed
originally submitted by @briansoden
* cleaned up Python formatting 
* removed unused variables and imports
* removed debugging lines
* removed deprecated font tag in html template
CI
**Checklist:**
=> Forcing feedback fork

templates/runtime_config.jsonc, templates/runtime_config.yml
=> more config file updates

.github/workflows/sphinx_action.yml, diagnostics/TC_Rain/doc/TC_Rain.rst, diagnostics/albedofb/doc/surface_albedo_feedback.rst, diagnostics/example_multicase/doc/example_multicase.rst, diagnostics/stc_eddy_heat_fluxes/doc/stc_eddy_heat_fluxes.rst, diagnostics/stc_ozone/doc/stc_ozone.rst, diagnostics/stc_qbo_enso/doc/stc_qbo_enso.rst, diagnostics/stc_spv_extremes/doc/stc_spv_extremes.rst, diagnostics/stc_vert_wave_coupling/doc/stc_vert_wave_coupling.rst, diagnostics/top_heaviness_metric/doc/top_heaviness_metric.rst, doc/conf.py, doc/copy_external_docs.py, doc/sphinx/dev_cheatsheet.rst, doc/sphinx/dev_coding_tips.rst, doc/sphinx/dev_guidelines.rst, doc/sphinx/fmwk_preprocess.rst, doc/sphinx/pod_requirements.rst, doc/sphinx/pod_settings.rst, doc/sphinx/ref_cli.rst, doc/sphinx/ref_conventions.rst, doc/sphinx/ref_data.rst, doc/sphinx/start_config.rst, doc/sphinx/start_install.rst, doc/sphinx/start_multirun.rst, doc/sphinx/start_overview.rst, src/data_sources.py, src/xr_parser.py, tools/catalog_builder/doc/catalog_builder.rst
Clean up docs and sphinx bulld action
**Checklist:**
=> More doc updates

src/environment_manager.py
* change subprocessRuntimePodWrapper to instantiate object from POD argument passed to init method
* fix abstractenvironmentmanager run method
* clean up dead lines in environment_manager
**Checklist:**
=> clean up environment_manager

src/environment_manager.py, src/util/filesystem.py
clean up filesystem.py formatting and multiple type hint specs
**Checklist:**
=> More fixes

tools/catalog_builder/catalog_builder.py
* define DRS specific GFDL pp catalog attributes relative to length o the file object
* refine checks for standard_name and long_name attributes
* add cell_methods and cell_measures attributes
* define activity_id and institution_id as GFDL for gfdl pp parser
**Checklist:**
=> Fix gfdl parser in catalog builder

data/cmip6-cmor-tables/Tables/CMIP6_CV.json
cron: update CMIP6_CV -- 2024-04-24T11:34
**Checklist:**
=> update cmip6 cmor tables

data/gfdl-cmor-tables/gfdl_to_cmip5_vars.csv, data/gfdl-cmor-tables/gfdl_to_cmip5_vars.json, data/gfdl-cmor-tables/gfdl_to_cmip6_vars.json
Conversion of csv cmip tables into JSON. 
**Checklist:**
=> add translated JSON files

src/preprocessor.py, src/util/datelabel.py
add math import for the int to date conversion
**Checklist:**
- [ x] The repository contains no extra test scripts or data files
=> update imports in preprocessor.py

src/data_model.py, src/preprocessor.py
* fix issues with the precip rate and level extraction edit_request functions 
**Checklist:**
=> More pr stuff

src/preprocessor.py, src/translation.py, src/xr_parser.py
=> fix pp query logic

src/xr_parser.py
get attribute checking back into effect by searching for missing attrs in var.encoding.
**Checklist:**
- [ x] The repository contains no extra test scripts …
=> add logic to check_metadata to search in ds_var.encoding

src/preprocessor.py
add chunks: auto to xr_open_kwargs
remove call to rename_dataset_keys from preprocessor query-no longer needed clean up CropDateRangeFunction and update key refs to use new xarray structure from catalog
**Checklist:**
=> Fix outstanding preprocessor issues

diagnostics/EOF_500hPa/EOF_500hPa.py, diagnostics/EOF_500hPa/compute_anomalies.ncl, diagnostics/EOF_500hPa/eof_natlantic.ncl, diagnostics/EOF_500hPa/eof_npacific.ncl, diagnostics/EOF_500hPa/settings.jsonc
* update POD environment variables
* fix file formatting
* change axis def to uppercase in pod settings file
**Checklist:**
=> Fix issues inf EOF_500hpa POD

diagnostics/EOF_500hPa/compute_anomalies.ncl, src/util/path_utils.py
* add model/netCDF subdirectory back to PodPathManager.setupPodPaths so that existing refs are not broken in PODs
* redefine date_offset variable in EOF500_hpa.compute_anomalies using the convention env var instead of the date_int_offset env_var that is no longer set
**Checklist:**
=> fix EOF500hPa issues

data/CM4_proto_diag_table.txt, templates/mdtf_gfdl.csh
* move CM4 diag table to data directory
* move mdtf_gfdl.csh template to templates directory and update variables the csh file will need additional mods when ready to test with frepp
**Checklist:**
=> move gfdl ref files

src/xr_parser.py
=> add function to replace units on time coord in varlist

src/preprocessor.py
fix precipratetofluxconversion.edit_request method to only apply changes to variable translation attribute if the pod standard_name differs from the convention standard_name
**Checklist:**
=> fix precipratetofluxconversion edit_request method

.github/PULL_REQUEST_TEMPLATE.md, doc/conf.py, doc/sphinx/dev_guidelines.rst, doc/sphinx/dev_start.rst, setup.py, src/conda/_env_synthetic_data.yml, src/conda/env_NCL_base.yml, src/conda/env_NCL_base_micromamba.yml, src/conda/env_R_base.yml, src/conda/env_base.yml, src/conda/env_base_micromamba.yml, src/conda/env_dev.yml, src/conda/env_python3_base.yml, src/conda/env_python3_base_micromamba.yml
Update conda environment files to Python 3.12, and package versions if necessary for compatibility
**Checklist:**
=> update conda envs to python 3.12

src/data_model.py, src/environment_manager.py, src/output_manager.py, src/pod_setup.py, src/preprocessor.py, src/translation.py, src/util/basic.py, src/varlist_util.py, src/xr_parser.py
* Fix outstanding issues in the plev attribute configuration in the translation module, and the alternate variable setup in the varlistentry_util.from_struct call.
* fix formatting in docstrings and elsewhere
**Checklist:**
=> Fix more issues

doc/sphinx/start_config.rst
Add information about the GFDL catalog builder to the documentation.
**Checklist:**
=> Add cat documentatation

src/preprocessor.py
The previous iteration of this sort relied on info supplied by esm_intake. This information would not always be supplied, thus it had to be changed to rely on something else. 
**Checklist:**
=> change time sort in preprocessor to rely on time coord

src/preprocessor.py, src/xr_parser.py
* fix hr -> 1hr freq conversion in pp query
* refine query variable definition
* fix logic in check_coord_bounds to account for undefined bounds values in xarray dataset instead of automatically calling cf assessor check_bounds and erroring out if it fails.
**Checklist:**
=> Fix issues in pp query

src/preprocessor.py, src/util/catalog.py, src/util/datelabel.py
* Add crop_date_range routine to preprocessor that operates on each variable xarray read from the catalog subset for each case
* Replace start_time and end_time entries with time_range entry in catalog generated by the preprocessor
**Checklist:**
=> Reimplement crop date range capability

diagnostics/forcing_feedback/settings.jsonc, src/conda/env_dev.yml, src/preprocessor.py
Move the drop attributes loop in query to a separate function in the preprocessor
**Checklist:**
=> Create drop attributes func

src/conda/env_dev.yml
Add kerchunk and profiling packages to the MDTF_dev conda environment file.
**Checklist:**
=> Update mdtf dev env file

src/conda/env_python3_base.yml
Associated PR #736  
**Checklist:**
=> add needed packages for MDSL POD to env_python3_base.yml

doc/conf.py, setup.py
=> change version to 4.2 in doc/conf.py and setup.py

doc/sphinx/start_install.rst
update instructions for linking conda binaries and env dirs for centrally managed conda dists
**Checklist:**
=> update installation instructions

.github/workflows/docker-build-and-push.yml
=> push container on version tag

tools/run-MDTF/scripts/gen_index.py
=> My pip refactor

data/fieldlist_CMIP.jsonc, diagnostics/mar/SST_bias_NOAA_OISSTv2/SST_bias_NOAA_OISSTv2.ipynb, diagnostics/mar/SST_bias_NOAA_OISSTv2/settings.jsonc, src/conda/env_dev.yml, src/conda/env_python3_base.yml, src/conda/env_python3_base_micromamba.yml, tools/run-MDTF/config/pod_config.json, tools/run-MDTF/doc/README.md, tools/run-MDTF/run-MDTF.sh, tools/run-MDTF/run-MDTF_frepp.csh, tools/run-MDTF/scripts/gen_config.py
* clean up formatting
* add option to specify convention
* add check for catalog in output_dir before generating a new one 
* add the --slow cli option to the fre catalog builder so that the standard_name entry is populated with correct information
**Checklist:**
=> refine MDTF-run script
